{% set name = "simwrapper" %}
{% set version = "1.8.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/simwrapper-{{ version }}.tar.gz
  sha256: 10e00dc0ba841a6f3f69c2d6afb5afe87d3936b0aff08deaac313fedb3c69318

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - simwrapper = simwrapper.cli:cli

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - click
    - python >=3.6

test:
  imports:
    - simwrapper
  commands:
    - pip check
    - simwrapper --help
  requires:
    - pip

about:
  home: https://github.com/simwrapper/simwrapper-python-tools
  summary: Python support library for SimWrapper data visualization tool
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - billyc
